services:
  - type: web
    name: adaptive-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: API_KEY  # Added API_KEY environment variable
        sync: false
      - key: WEB_CONCURRENCY  # Added worker configuration
        value: "2"
    healthCheckPath: /api/health
